# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='major',
        ),
        migrations.RemoveField(
            model_name='member',
            name='title',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
