# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:06
from __future__ import unicode_literals

import announcements.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(verbose_name='Announcement release')),
                ('end_date', models.DateTimeField(verbose_name='Announcement expiration')),
                ('data', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to=announcements.models.get_file_path)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
