# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20170426_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='file_title',
            field=models.CharField(default='No file', max_length=30),
        ),
    ]
