# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160518_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Del Vento', 'Del Vento'), ('Dining Area', 'Dining Area'), ('Library', 'Library'), ('Elk Room', 'Elk Room'), ('Game Room', 'Game Room'), ('Movie Room', 'Movie Room')], max_length=50),
        ),
    ]
