# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170404_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Cluster', 'Cluster'), ('Del Vento', 'Del Vento'), ('Dining Area', 'Dining Area'), ('Elk Room', 'Elk Room'), ('Game Room', 'Game Room'), ('Library', 'Library'), ('Movie Room', 'Movie Room'), ('Taproom', 'Taproom'), ('Colonial', 'Colonial')], max_length=50),
        ),
    ]
