# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170404_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('IMs', 'IMs'), ('Friday Party', 'Friday Party'), ('Semiformal', 'Semiformal'), ('Study Break', 'Study Break'), ('Sophomore Dinner', 'Sophomore Dinner'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Cluster', 'Cluster'), ('Del Vento', 'Del Vento'), ('Dining Area', 'Dining Area'), ('Elk Room', 'Elk Room'), ('Game Room', 'Game Room'), ('Library', 'Library'), ('Movie Room', 'Movie Room'), ('Taproom', 'Taproom'), ('Colonial', 'Colonial')], default='Colonial', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open'), ('Hidden', 'Hidden')], default='Hidden', max_length=10),
        ),
    ]
