# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170407_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('IMs', 'IMs'), ('Friday Party', 'Friday Party'), ('Semiformal', 'Semiformal'), ('Study Break', 'Study Break'), ('Sophomore Dinner', 'Sophomore Dinner'), ('Language Table', 'Language Table'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, upload_to=events.models.get_file_path),
        ),
    ]
