# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170407_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('IMs', 'IMs'), ('Friday Party', 'Friday Party'), ('Semiformal', 'Semiformal'), ('Study Break', 'Study Break'), ('Sophomore Dinner', 'Sophomore Dinner'), ('Language Table', 'Language Table'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, upload_to=events.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Cluster', 'Cluster'), ('Del Vento', 'Del Vento'), ('Dining Area', 'Dining Area'), ('Elk Room', 'Elk Room'), ('Game Room', 'Game Room'), ('Library', 'Library'), ('Movie Room', 'Movie Room'), ('Taproom', 'Taproom'), ('Colonial', 'Colonial'), ('Other', 'Other (See Description)')], default='Colonial', max_length=20),
        ),
    ]
