# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170414_1656'),
        ('events', '0007_auto_20170421_1511'),
    ]

    operations = [
    ]
