# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_merge_20170422_2131'),
        ('events', '0008_merge_20170425_0151'),
    ]

    operations = [
    ]
