# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20170425_1245'),
        ('events', '0009_merge'),
        ('events', '0009_merge_20170428_1410'),
        ('events', '0010_auto_20170426_1306'),
    ]

    operations = [
    ]
