# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_merge_20170511_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Cluster', 'Cluster'), ('Del Vento', 'Del Vento'), ('Dining Area', 'Dining Area'), ('Elk Room', 'Elk Room'), ('Game Room', 'Game Room'), ('Library', 'Library'), ('Movie Room', 'Movie Room'), ('Taproom', 'Taproom'), ('Lawn', 'Lawn'), ('Colonial', 'Colonial'), ('Other', 'Other (See Description)')], default='Colonial', max_length=20),
        ),
    ]
