# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_merge_20170511_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('No RSVP', 'No RSVP'), ('Open', 'Open'), ('Closed', 'Closed'), ('Hidden', 'Hidden')], default='Hidden', max_length=10),
        ),
    ]
