# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20170513_1927'),
        ('events', '0013_auto_20170519_0823'),
    ]

    operations = [
    ]
