"""
Django settings for colonialsite project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# --- IMPORTANT SETTINGS ---

# SECRET_KEY
DEBUG = True

# EMAIL_HOST_USER
# EMAIL_HOST_PASSWORD

# TIGERBOOK_LOGIN
# TIGERBOOK_PW

# Used in coloauth.middleware
# Default Login is automatically added
# in RE format
LOGIN_EXEMPT_URLS = [r'^accounts/logout($|.*)', r'^staff/login($|.*)', r'^staff/logout($|.*)',]

STAFF_LOGIN_URL = '/staff/login/'
STAFF_LOGIN_REDIRECT = '/announcements/'


# --- APPLICATIONS AND MIGRATIONS ---

INSTALLED_APPS = [
    'announcements.apps.AnnouncementsConfig',
    'coloauth.apps.ColoauthConfig',
    'dashboard.apps.DashboardConfig',
    'events.apps.EventsConfig',
    'members.apps.MembersConfig',
    'menus.apps.MenusConfig',
    'reservations.apps.ReservationsConfig',
    'webpack_loader',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'cas',
    'django_filters',
]


# --- URLS ---

LOGIN_URL = '/accounts/login/'
CAS_SERVER_URL = 'https://fed.princeton.edu/cas/'
ROOT_URLCONF = 'colonialsite.urls'


# --- MISCELLANEOUS BACKEND ---

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
DATABASES = {
    'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'PAGE_SIZE': 100,
    'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    #'cas.backends.CASBackend',
    'coloauth.backends.RestrictedCASBackend',
]

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cas.middleware.CASMiddleware',
    'coloauth.middleware.LoginRequiredMiddleware',
]

X_FRAME_OPTIONS = 'DENY'


# --- FRONTEND ---

WEBPACK_LOADER = {
        'DEFAULT': {
            'BUNDLE_DIR_NAME': 'bundles/',
            'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
            }
        }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --- FILE SETTINGS ---

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'assets'),
]

# Path to file uploads (upload images)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# --- MISCELLANEOUS ---

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/New_York'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# --- APPLICATION SPECIFIC ---

SOPHOMORE_YEAR = '2020'
JUNIOR_YEAR = '2019'
SENIOR_YEAR = '2018'


# --- LOCAL AND SENSITIVE SETTINGS ---

try:
    from local_settings import *
except ImportError:
    pass

try:
    from production_settings import *
except ImportError:
    pass