# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20170224_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='menus',
            field=models.ManyToManyField(to='menus.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='meal_permissions',
            field=models.CharField(choices=[('NG', 'No Guests or Meal Exchanges'), ('NME', 'No Meal Exchanges'), ('SGO', 'Sophomore Guests Only'), ('NTO', 'No Boxes for Take-out'), ('ALL', 'Guests and Meal Exchanges Allowed')], default='ALL', max_length=10),
        ),
    ]
