# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0006_auto_20170422_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Soups', 'Soups'), ('Hot Line', 'Hot Line'), ('On the Grill', 'On the Grill'), ('On the Chafer', 'On the Chafer'), ('Dessert', 'Dessert')], max_length=20)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='menus',
            field=models.ManyToManyField(to='menus.MenuCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('dish', 'reviewingUser')]),
        ),
    ]
