# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20170422_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dish',
            name='dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='kosher_halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='nut_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='soy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
