# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 01:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20170422_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='menu',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='meal date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Brunch', 'Brunch'), ('Dinner', 'Dinner')], default='Dinner', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='meal_permissions',
            field=models.CharField(choices=[('NG', 'No Guests or Meal Exchanges'), ('NME', 'No Meal Exchanges'), ('SGO', 'Sophomore Guests Only'), ('NTO', 'No Boxes for Take-out'), ('ALL', 'Guests and Meal Exchanges Allowed')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
