# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-11 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_auto_20170426_1306'),
        ('menus', '0009_auto_20170427_2115'),
    ]

    operations = [
    ]
