# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_auto_20170512_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
