# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0013_auto_20170519_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='avg_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='dish',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
