# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='approved',
        ),
        migrations.AddField(
            model_name='reservation',
            name='approval',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Denied', 'Denied')], default=datetime.datetime(2016, 4, 21, 13, 59, 2, 436415, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.CharField(choices=[('Elk Room', 'Elk Room'), ('Del Vento', 'Del Vento Room'), ('Library', 'Library'), ('DHall', 'Dining Hall'), ('Taproom', 'Taproom'), ('Movie Room', 'Movie Room')], max_length=10),
        ),
    ]
