# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20160421_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 21, 14, 25, 0, 625100, tzinfo=utc), verbose_name='creation date/time'),
            preserve_default=False,
        ),
    ]
