# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.CharField(choices=[('Elk Room', 'Elk Room'), ('Del Vento', 'Del Vento Room'), ('Library', 'Library'), ('DHall', 'Dining Hall'), ('Taproom', 'Taproom'), ('Movie Room', 'Movie Room'), ('Rec Room', 'Rec Room'), ('Cluster', 'Cluster'), ('Game Room', 'Game Room')], max_length=10),
        ),
    ]
