# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20160502_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='requestor',
            new_name='requester',
        ),
    ]
