# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20170422_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
