# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_pos', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('class_year', models.CharField(max_length=10)),
            ],
        ),
    ]
