# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170421_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='officer_pos',
            field=models.CharField(blank=True, choices=[(b'President', b'President'), (b'Vice President', b'Vice President'), (b'Social Chair', b'Social Chair'), (b'Treasurer', b'Treasurer'), (b'House Manager', b'House Manager'), (b'Beverage Chair', b'Beverage Chair'), (b'IM Chair', b'IM Chair'), (b'Community Chair', b'Community Chair'), (b'Publicity Chair', b'Publicity Chair'), (b'Assistant Social Chair', b'Assistant Social Chair'), (b'Sophomore Representative', b'Sophomore Representative'), (b'Finance Chair', b'Finance Chair'), (b'Colonial Development Lead', b'Colonial Development Lead')], max_length=30, verbose_name=b'Officer Position'),
        ),
    ]
